import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import { AlertProvider } from "@/context/AlertContext";
import Alert from "@/app/components/ui/Alert";
import Navbar from "./components/navbar/navbar";
import Footer from "./components/footer/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex flex-col min-h-screen bg-[#FFF7F6]"
      >
        <AuthProvider>
          <AlertProvider>
            <Alert /> {/* Renderiza las alertas globales */}
            <Navbar />
            <main className="flex-grow bg-[#ffffff]">{children}</main>
            <Footer />
          </AlertProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
